# based on https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
name: dump context
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

env:
  REPOSITORY_NAME: $(echo ${{ github.repository }} | awk -F'/' '{print $2}')

jobs:
  dump_contexts_to_log:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: echo repository name 1
        run: echo ${{ github.repository }} | awk -F'/' '{print $2}'
      - name: echo repository name 2
        run: echo ${{ github.event.repository.name }}
      - name: echo env
        run: echo ${{ env.REPOSITORY_NAME }}
      - name: Dump github context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
